name: Shardmanager Gradle CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean shadowJar
    - name: Build Dockerimageg
      env:
        IMAGE: theleede/fivebot
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        docker build -t ${IMAGE} . -f Dockerfile
        docker tag ${IMAGE} ${IMAGE}:${GITHUB_SHA::8}
        docker push ${IMAGE}
    - name: Tag Image Master
      if: github.ref == 'refs/heads/master'
      env:
        IMAGE: theleede/fivebot
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker tag ${IMAGE} ${IMAGE}:master
        docker push ${IMAGE}